---
 - hosts: control
   roles:
    - { role: aws-s3-getbuild, aws_access_key: "AKIAJZKNBNKMUAJIM2AQ", aws_secret_key: "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" }  

 - hosts: aws
   roles:
    - { role: aws-customerapi, remote_install_package: "C:\\Deployment\\CustomerAPITest.zip", remote_install_path : "C:\\WebApps\\CustomerAPITest", setup_drive_destination : "C:\\WebApps\\CustomerAPITest", main_app_pool : "CustomerAPITest"}
    #- mbs-monitor
     
